version: '3'
services:
  reverse-proxy:
    image: traefik:2.5
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb_seed:
    image: bitnami/mongodb:4.2
    volumes:
      - "./seed_db/seed:/seed"
      - "./seed_db/mongo_import.sh:/mnt/mongo_import.sh"
    command: 
      - "sh"
      - "-c"
      - "chmod u+x /mnt/mongo_import.sh && /mnt/mongo_import.sh"
    user: "0:0"
    depends_on:
      - mongodb
    restart: on-failure
  mongodb:
    image: bitnami/mongodb:4.2
    volumes:
      - "mongodb_data:/bitnami"
  catamel:
    #image: dacat/catamel:latest
    image: scicatproject/backend:v0.0.5
    depends_on:
      mongodb:
        condition: service_started
      local-rabbitmq:
        condition: service_healthy
    volumes:
      - ./config/catamel/config.local.js:/usr/src/app/server/config.local.js
      - ./config/catamel/datasources.json:/usr/src/app/server/datasources.json
      - ./config/catamel/providers.json:/usr/src/app/server/providers.json
      - ./config/catamel/component-config.local.json:/usr/src/app/server/component-config.local.json
    labels:
      - "traefik.http.routers.catamel.rule=PathPrefix(`/api`, `/auth`, `/explorer`)"
      - "traefik.http.routers.catamel.entrypoints=web"
      - "traefik.http.routers.catamel.rule=Host(`catamel.localhost`)"
  catanie:
    #image: dacat/catanie:latest
    image: scicatproject/frontend:v4.0.0
    #image: dacat/catanie:2431284a58361320b334162def0323e5e017aaeaproduction
    depends_on:
      - catamel
    volumes:
      - ./config/frontend/config.json:/usr/share/nginx/html/assets/config.json
    labels:
      - "traefik.http.routers.catanie.rule=PathPrefix(`/`)"
      - "traefik.http.routers.catanie.entrypoints=web"
      - "traefik.http.routers.catanie.rule=Host(`catanie.localhost`)"
  search-api:
    image: dacat/panosc-search-api:latest
    depends_on: 
      - catamel
    labels:
      - "traefik.http.routers.panosc-search-api.rule=PathPrefix(`/panosc-api`, `/panosc-explorer`)"
      - "traefik.http.routers.panosc-search-api.entrypoints=web"
    environment:
      BASE_URL: "http://catamel:3000/api/v3"
      FACILITY: "SAMPLE-SITE"
  local-rabbitmq:
    hostname: local-rabbitmq
    build: 'rabbitmq/.'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=password
    volumes:
      - 'rabbitmq_data:/bitnami'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      start_period: 3s
      interval: 30s
      timeout: 10s
      retries: 5
  archive-mock:
    build: 'ScicatArchiveMock/.'
    depends_on:
      local-rabbitmq:
        condition: service_healthy
      catamel:
        condition: service_started
    environment:
      - "SCICAT_URL=http://catamel:3000/api/v3/"
      - "RABBITMQ_URL=local-rabbitmq"
      - "USERNAME=admin"
      - "PASSWORD=2jf70TPNZsS" 
volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local
